// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: items.sql

package repository

import (
	"context"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (
    board_id, title, description
) VALUES (
    ?, ?, ?
)
RETURNING id, board_id, title, description, completed, created_at, last_updated_at
`

type CreateItemParams struct {
	BoardID     int64  `json:"boardId"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem, arg.BoardID, arg.Title, arg.Description)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.LastUpdatedAt,
	)
	return i, err
}

const deleteItemByID = `-- name: DeleteItemByID :exec
DELETE FROM items
WHERE id = ?
`

func (q *Queries) DeleteItemByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteItemByID, id)
	return err
}

const getItemByID = `-- name: GetItemByID :one
SELECT
id, board_id, title, description, completed, created_at, last_updated_at
FROM items
WHERE items.id = ?
`

func (q *Queries) GetItemByID(ctx context.Context, id int64) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.LastUpdatedAt,
	)
	return i, err
}

const listItemsByBoardID = `-- name: ListItemsByBoardID :many
SELECT
id, board_id, title, description, completed, created_at, last_updated_at
FROM items
WHERE items.board_id = ?
ORDER BY items.created_at
`

func (q *Queries) ListItemsByBoardID(ctx context.Context, boardID int64) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listItemsByBoardID, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
			&i.LastUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemByID = `-- name: UpdateItemByID :one
UPDATE items
SET
    title = ?,
    description = ?,
    completed = ?,
    last_updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, board_id, title, description, completed, created_at, last_updated_at
`

type UpdateItemByIDParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Completed   bool   `json:"completed"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateItemByID(ctx context.Context, arg UpdateItemByIDParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, updateItemByID,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.ID,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.LastUpdatedAt,
	)
	return i, err
}
