// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"time"
)

type Board struct {
	ID            int64     `json:"id"`
	Name          string    `json:"name"`
	CreatedAt     time.Time `json:"createdAt"`
	LastUpdatedAt time.Time `json:"lastUpdatedAt"`
}

type Item struct {
	ID            int64     `json:"id"`
	BoardID       int64     `json:"boardId"`
	Title         string    `json:"title"`
	Description   string    `json:"description"`
	Completed     bool      `json:"completed"`
	CreatedAt     time.Time `json:"createdAt"`
	LastUpdatedAt time.Time `json:"lastUpdatedAt"`
}
